import type { Metadata } from "next";

import Providers from "@/components/Providers/Providers";
import { georgia, inter } from "./fonts";
import clsx from "clsx";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const classes = clsx(georgia.variable, inter.variable, "scroll-smooth");
  return (
    <html lang="en" className={classes}>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
